# -*- mode: ruby -*-
# vi: set ft=ruby :

### https://joelkleier.com/posts/2022-07-05-podman-m1/
# NOTE need vagrant >= 2.4.0

Vagrant.configure("2") do |config|
  # for a "normal" provider, like VirtualBox, using a vm
  config.vm.box = "ubuntu/bionic64"

  # for the docker/podman provider, specifically
  config.vm.provider "docker" do |d, override|
    # need to tell vagrant not to try and manage a box of any kind
    override.vm.box = nil

    override.ssh.insert_key = true

    d.build_dir = "."
    d.dockerfile = "Containerfile"
    d.has_ssh = true
    d.privileged = true

    # need to tell podman to forward the ssh port
    override.vm.network "forwarded_port", guest: 22, host: 2222
  end

  # open up to the folder that should be mounted to a folder on the podman
  # machine, which might be itself mapped to a volume on the local host system
  # depending on your podman machine configuration
  config.ssh.extra_args = ["-t", "cd /vagrant; bash --login"]

  # for an app running in the vagrant controlled container
  #config.vm.network "forwarded_port", guest: 8000, host: 8000

  config.vm.provision "shell", inline: <<-SHELL
    # fun init stuff here
  SHELL
end
